name: Console TDM
baseurl: /console-tdm
url: http://dopsi.github.io
description: The official Console TDM website

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
