# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Console TDM
email: dopsi.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a fork of console-tdm by mytbk. console-tdm aims to reproduce the 
  functionnality of a traditionnal display manager using only console tools.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dopsi.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  dopsi

# Build settings
markdown: kramdown
